### ISSUE TITLE
routeEnhancer configuration for typo3 v9

### ISSUE THREAD

**Issue by X-Tender** [teaminmedias-pluswerk/ke_search#279]
I've tried to create a routeEnhancer config to recieve nice URLs but didn't went pretty far.
That's my config currently:
```
  Search:
    type: Plugin
    limitToPages: [31]
    routePath: '/{sword}/{page}/{resetFilters}/{sortByField}/{sortByDir}'
    namespace: 'tx_kesearch_pi1'
    requirements:
      _sword: '[a-zA-Z0-9]+'
      _page: '[0-9]+'
      _resetFilters: '[10]'
      _sortByField: '(^$|sortdate|title)'
      _sortByDir: '(^$|asc|desc)'
```
After a search the URL is the old, "unreadable" url. But the order functions for example ahve the nice looking URL (with cHash). When I click on a sorting then its ok. But after that the sorting links didn't have the page or sword in it.

Did someone have a working Configuration?
